version: '1.0'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    container_name: frontend
    networks:
      - app

  backend:
    build:
      context: ./model
    ports:
      - 8000:8000
    volumes:
      - ./model:/app
    container_name: backend
    networks:
      - app

networks:
  app:
    driver: bridge


# To run the application just type docker-compose up --build