version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    container_name: frontend

  backend:
    build:
      context: ./model
    ports:
      - 8000:8000
    volumes:
      - ./model:/app
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge
